### ISSUE TITLE
Contact Info Plus Map

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#103]
- [x]  add social media icons to the contact info section. Use the values from the site settings, just let them choose what ones they want to add here

- [x] Add optional buttons

- [x] (bumped to #124) Can we add some smart functionality to add a link to the JCU maps at https://maps.jcu.edu.au/ so that they popup with the building in question highlighted? `url/campus/campus-name/?location=building-id`
or just add instructions on how to build the url into the documentation and let them use an optional button?

- [x] (bumped to #124) Add documentation on how to generate the URL that needs to be added for the map.

**Comment by davidjb** [comment]
In case this hasn't been handled already, for the 3rd/4th points above (generating the URL), the interactive maps allow you to get the URL to a building -- left-click a building or feature (or right-click anywhere), click Share/Bookmark, and click Copy URL.

**Comment by DanielBaird** [comment]
Created #124 to split off the JCU Map and URL documenting items.. the rest of these items are all done!
