### ISSUE TITLE
Table formatting

### ISSUE THREAD

**Issue by DanielBaird** [jcu-eresearch/matrix-helpers#104]
@PaulineLawrey suggested we should have some nice looking table formats for people to use on tables in their wysiwyg text areas.

Maybe there are some table formats already available from Bootstrap, in which case we just need to document the required classes.

**Comment by DanielBaird** [comment]
Turns out some of the Bootstrap table styles are already available.  Feels like David has been here already (gif attached, give it a few seconds to load)

@PaulineLawrey you reckon we can close this, or should we keep this issue to remind us to add table-formatting to docs somewhere?

![tables](https://cloud.githubusercontent.com/assets/25352/26140281/312657a0-3b19-11e7-8e45-d739cdd5cb7d.gif)

**Comment by davidjb** [comment]
Table base classes are now applied by an editor (Viper) patch and are all now responsive by default 👍
