### ISSUE TITLE
Images should not be clickable by default in Basic Block

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#106]
Shannon and I were thinking that it might be good if the default behaviour was for the images not to be clickable but to have enabling lightbox as an option. Either just for that photo or maybe for all the photos on the page if this is the lightbox behaviour. 
Part of the problem with the current behaviour is that the image just replaces the site and there is no title or anything and you have to use the browser back button to return. Lightbox helps with this as it pops up over the site and has an easily seen close button.
Note: I haven't checked the behaviour on a mobile device though.

**Comment by davidjb** [comment]
Edit: retracting previous statements.

By default, we already do lightbox by default (eg https://www.jcu.edu.au/orpheus-island/research/_noproxycache) for images against a Basic Block.  So is this suggestion to add an option to allow lightbox toggling on/off?

As for the case of linking to the image resource itself (eg needing the back button), have you got an example of a page where this is happening?

**Comment by davidjb** [comment]
We've now got Image Varieties being consistent with the existing behaviour and have decided to leave opening a lightbox as the behaviour for all images.  If we have a specific use case come up where someone needs the images unlinked, we can add a metadata field to disable the current behaviour.

Closing for now.
