### ISSUE TITLE
Spacing between content block heading and subhead too tight 

### ISSUE THREAD

**Issue by DanielBaird** [jcu-eresearch/matrix-helpers#111]
On non-landing pages, a content block subheading is a bit to close to the heading above it.  On landing pages the heading text is a bit larger and the spacing to the subheading is about right.

This seems like it should be easy to tweak but the existing pattern of headings looks like this:

```
<h2 class="...">
    The Main Heading
    <br>
    <span class="...">the subheading</span>
</h2>
```
...which means the span will use an effective `line-height` of the max of the `h2` `line-height` and its own `line-height`.

Explored in this codePen: https://codepen.io/danielbaird/pen/NjZRMz

Probably the solution for this is to just re-do all our heading layouts to be more like:

```
<header>
    <h2>The Main Heading</h2>
    <p>The sub-heading</p>
</header>
```
..then we'd have the usual control over whitespace between heads and subheads.

**Comment by PaulineLawrey** [comment]
After discussion we agreed that it would be an acceptable solution to break the Title and Subtitle into two separate semantic elements. Although they are termed Title and Subtitle in the settings, sometimes the subtitle is in fact just another piece of information about this content block.  The Title will be a header and the Subtitle will be a paragraph with appropriate styling.

**Comment by davidjb** [comment]
https://github.com/jcu-eresearch/matrix-helpers/blob/master/web-framework/content-templates/common/title-subtitle-paint-layout.html#L27 is what we need to move into `<p class="lead">` after the heading element.
