### ISSUE TITLE
Review CCT behaviour on the Landing page theme and update if necessary

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#116]
Not all of the content container templates work nicely on the landing page. They need to be tested and fixed if necessary.
CCTs to review are:

- [x] Summary Cards
- [x] Image Gallery
- [x] Content info plus map
- [x] Introductory text
- [x] Process Steps
- [x] Text plus feature number
- [x] Text plus 3 featured numbers
- [x] Twitter stream

**Comment by DanielBaird** [comment]
especially the things this site needs: https://www.jcu.edu.au/state-of-the-tropics

**Comment by DanielBaird** [comment]
Wow, almost all of these are not fitting in to the landing page properly.

**Comment by DanielBaird** [comment]
All done!
