### ISSUE TITLE
document "Twitter stream" content block

### ISSUE THREAD

**Issue by DanielBaird** [jcu-eresearch/matrix-helpers#117]
Twitter stream needs docs in the guide site, and also the SVG diagram page

**Comment by DanielBaird** [comment]
You know who *loves* writing documentation?  Shan, Shan loves writing documentation :)

**Comment by davidjb** [comment]
Done @ https://www.jcu.edu.au/web-framework-guide/content-blocks/twitter-stream-plus-text/
