### ISSUE TITLE
Filed titles have each word capitalised when displayed in Image Gallery

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#120]
See https://www.jcu.edu.au/web-framework-guide/content-blocks/create-a-content-block/_noproxycache
The Screenshots image gallery is the one to look at. The image titles all have every word capitalised but if you look at the assets in question their **Title** fields do not have every word capitalised.

e.g. asset 435789 (the 1st image) has the Title of *Page tools > Edit > Edit page* content but it displays as *Page Tools > Edit > Edit Page Content* 

When we output the title in the Image Gallery listing asset we don't do this, the only processing we do is `escapequotes` so when is this being done?

**Comment by PaulineLawrey** [comment]
This is being done in the CSS, we should change this so that it displays as the editor intended.

**Comment by davidjb** [comment]
Done, I took out the CSS rule that was capitalising the captions and adjusted the HTML to use the FIgure component (https://web.jcu.io/content/figures/).  This'll make for consistent captions and labels.  

I also took the moment to adjust Calendar events to use the same syntax too.
