### ISSUE TITLE
Doc example: bunch of logos, using Image Gallery

### ISSUE THREAD

**Issue by DanielBaird** [jcu-eresearch/matrix-helpers#126]
We need a doc example of logos, using Image Gallery. Shan used an awkward looking Thumbnail Grid to render a bunch of logos in the State-of-the-Tropics site.

**Comment by davidjb** [comment]
Here's an example I've just made up: https://www.jcu.edu.au/web-framework-guide/inspiration/#image-gallery-logos

Much nicer.
