### ISSUE TITLE
Summary Cards Print Layout needs fixing

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#134]
1. The image links are being displayed as part of the image. This makes it all look very bizarre. To fix this we need to move the `summarycard-image-wrapper` class off the div that wraps the `<a>` and `<image>` tags and down onto the `<image>`. This controls the shape of the image (circle or natural) and is what is causing the problem. We just have to check that this doesn't break any other CSS layout functionality.

1. The buttons in the grid cards have the URL added into them inside the button outline and look terrible.

**Comment by DanielBaird** [comment]
An issue has been created against the web framework https://github.com/jcu/web-framework/issues/17 in support of this.

**Comment by PaulineLawrey** [comment]
1. Fixed (see SHA f0867e3120a90135b8514c669d90470176081974)
2. Nothing that can be done about this.
