### ISSUE TITLE
Pages contents not fully printed by Chrome

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#135]
Various pages from our web-framwork sites do not completely print when using Chrome. Of the pages I tested, they all printed completely under Firefox and Internet Explorer (assuming we are choosing not to print the cobranding footer and buttons).

Note: I did not print all these pages to paper, just viewed them in the print preview and printed to Adobe PDF.

Pages that didn't fully print were:

- https://www.jcu.edu.au/daintree

- https://www.jcu.edu.au/web-framework-guide/inspiration/_noproxycache

A page that does fully print is:

- https://www.jcu.edu.au/prawn-breeding-hub/research/family-production-component/_noproxycache

I also tested a page from the corporate site and it seemed to print fully:

- https://www.jcu.edu.au/courses-and-study/courses/bachelor-of-medical-laboratory-science

**Comment by davidjb** [comment]
Hmm, so on Firefox Dev Edition the first link doesn't print fully either -- mine ended after the `Facilities` page for Daintree, but the Guide page looks okay.  Where do yours end?

Just a heads up that I omit the footers entirely on print to avoid waste, so you'll never see that.  (the logo/s would just have been duplicated plus social media links aren't overly useful on print).

**Comment by PaulineLawrey** [comment]
For the Daintree page I got the Location and Contact details printed but not the map background but assumed the backgrounds are being left out on purpose.
But none of the buttons are printed. I'm running 52.2.0 (32-bit) and it says it is up to date.
