### ISSUE TITLE
Process Step Layout issues - double digit problems

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#137]
When I get to double digits the process step layout doesn't quite work. The numbers overlap the content.
See: https://www.jcu.edu.au/ed1441/module-1/week-3/_noproxycache

**Comment by davidjb** [comment]
With this, we also need to check responsiveness for 2- and 3-digit steps.

**Comment by DanielBaird** [comment]
Fixed by 551e064bc2d1f6babd94934824675effc95edb83 for two-digit step numbers. Three digit numbers are still poorly rendered in some situations, but fixing that in a simple way required making compromises for how single-digit numbers looked.
