### ISSUE TITLE
Matrix 5.4 broke the use of `with_get` in %asset_*% keywords

### ISSUE THREAD

**Issue by davidjb** [jcu-eresearch/matrix-helpers#50]
Our old references to pass the metadata contents to our HTML phrasing cleaner:
```
  %asset_assetid^notempty:382695^as_asset:asset_contents^with_get:text={asset_metadata_template.title.title}%
```

Got broken with the upgrade to 5.4.0.3.  I'm unsure where the breakage happened, but it looks like this https://squizmap.squiz.net/matrix/9953 was the issue where they tried to fix `with_get` in asset listings.  It's the only change log regarding `with_get` between 5.3.3 and 5.4.0.3.

At any rate, the `with_get` keyword modifier no longer works here so we need to get creative.

**Comment by davidjb** [comment]
Now we're using the slightly-more-formalised `%asset_contents_paint_1234%` keyword.  See https://squizmap.squiz.net/matrix/8847 for the implementation notes.

**Comment by DanielBaird** [comment]
I'm using these with a trailing comment describing what the magic number does, like this:

```
!!DON'T DO THIS!!
%asset_contents_paint_386956%<!-- 386956: title with only phrasing-content html tags left in --> 
```

Update: having no space between the final `%` and the `<!--` makes it render the comment as content... I'll test Matrix comments described below

Update 2: yes Matrix comments are the way to go.

``` html
%asset_contents_paint_386956%<!--@@ 386956: title with only phrasing-content html tags left in @@--> 
```

**Comment by davidjb** [comment]
Awesome.  Worth using a Matrix-only comment to save on page weight or would that cost more PHP time than we'd save?  Eg `<!--@@ Matrix strips this out @@-->`

**Comment by davidjb** [comment]
Going to close this off on account of #61 and the fact we've ceased using this approach. Also, the security risks here are too great.
