### ISSUE TITLE
Twitter feed on RHS column

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#85]
Add ability to add a twitter feed (or facebook) as a column on the RHS of the page. The Centres and Institutes primarily use Twitter as communications mechanism.

**Comment by davidjb** [comment]
Relates to #33, that original concept was about introducing the concept of "portlets" (like in Plone) for left and right side columns.

**Comment by DanielBaird** [comment]
Twitter feeds added via #97, and we aren't doing side columns any more, so wontfix this.
